### ISSUE TITLE
missing maven dependency hadoop-client

### ISSUE THREAD

**Issue by noaresare** [spotify/hdfs2cass#1]
When trying our our new normalized build environment foss-builder.spotify.net it turns out that the master branch of hdfs2cass doesn't build on a vanilla ubuntu 13.10 box due to a missing dependency org.apache.hadoop:hadoop-client:jar:2.0.0-mr1-cdh4.0.0

At the very least we should document where that dependency could be found in README.md

**Comment by rzvoncek** [comment]
I believe this is outdated now.
