### ISSUE TITLE
Please post sample data and schema creation files

### ISSUE THREAD

**Issue by sagpid** [spotify/hdfs2cass#4]
Hi,

We tried to use the program but found it hard to use, because the data format is Avro raw.  We created avro raw file but we have not yet succeeded in getting it to work

Here is the format that we tried.

{
  "namespace": "HdfsToCassandra",
  "name": "test_serializer",
  "type": "record",
  "fields": [
    { "name":"string1", "type":"string" },
    { "name":"int1", "type":"int" }
  ] }

In the read me file you mention 7 columns per row, is that required for every single key value?

**Comment by rzvoncek** [comment]
As a part of house-cleaning, I'll close this one as well. Feel free to open new issues if needed.
